### ISSUE TITLE
Reusable workflows are difficult to reuse

### ISSUE THREAD

**Issue by LouisBrunner** [aica-technology/.github#10]
This repo currently uses Reusable workflows to allow code reuse around the org. This makes it impossible to add more steps before the workflow (e.g. extra setup like adding private SSH keys). Moreover, the main workflow (`build-push-multi-arch`) does a lot of different things which prevent reuse.

I propose that we transform them to Composite Actions instead (here is a quick reference of the difference: https://cardinalby.github.io/blog/post/github-actions/dry-reusing-code-in-github-actions/) and break them into more granular chunks.

I am currently thinking:
 * `docker-build`: just doing buildx + qemu + docker build, even if you don't do multi-arch, this ensure you can build any arch on any host and makes it a very solid build step
 * `login-to-ghcr`: does the connection to GHCR
 * `ghcr-build`: same behaviour as `build-push-multi-arch` by composing the two above actions (+ ensuring the image prefix)
 * `write-file` stays as-is

This allows future GitHub workflows to be able to build for other registries than GHCR, allows to login to GHCR to just pull and still keeps an easy to maintain current behaviours.

**Comment by domire8** [comment]
I agree with the disadvantages of those workflows. When I created them, I thought that composite actions need their own repo. Is that a misconception?

**Comment by LouisBrunner** [comment]
@domire8 They use a slightly different format than workflows (90% is the same) and can be called in the exact same manner. Example of setup: https://github.com/aica-technology/.github/tree/feature/comp-actions/.github/actions, you can find an example of usage in the backend.
