### ISSUE TITLE
Update version of `docker-tag-from-git` action to >0.6.0 across all repos

### ISSUE THREAD

**Issue by eeberhard** [aica-technology/.github#20]
Issue https://github.com/aica-technology/.github/issues/16 was resolved in https://github.com/aica-technology/.github/pull/18 and tagged in version 0.6.0. 

It's easier to work with the latest `develop` images if they are automatically tagged, so all repositories that use the `docker-tag-from-git` action should have the version updated.

**Comment by domire8** [comment]
I believe that should do it.
